{
  "data": {
    "repository": {
      "pullRequest": null
    }
  },
  "errors": [
    {
      "type": "NOT_FOUND",
      "path": [
        "repository",
        "pullRequest"
      ],
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "message": "Could not resolve to a PullRequest with the number of 174519163."
    }
  ]
}
